services:
  surrealdb:
    image: surrealdb/surrealdb:v2.2.2
    env_file:
      - .env
    entrypoint:
      - /surreal
      - start
      - --user
      - $SURREALDB_USER
      - --pass
      - $SURREALDB_PASS
    ports:
      - 8080:8000

  minio:
    image: quay.io/minio/minio
    env_file:
      - .env
    entrypoint:
      - minio
      - server
      - /data
      - --console-address
      - ":9001"
    ports:
      - 9000:9000
    healthcheck:
      test:
        - CMD
        - curl
        - http://localhost:9000
      interval: 5s
      retries: 5
      timeout: 3s
